# official PHP docker image from https://hub.docker.com/_/php
image: php:7.3

# shell script
before_script:
- bash ci/docker_install.sh > /dev/null

test:app:
  script:
  - phpunit --configuration phpunit_helloworld.xml