# official PHP docker image from https://hub.docker.com/_/php
#image: php:5.6

# shell script
before_script:
- bash ci/docker_install.sh > /dev/null

test:5.6:
  image: 5.6
  script:
  - phpunit --configuration phpunit_helloworld.xml

test:7.3:
  image: 7.3
  script:
  - phpunit --configuration phpunit_helloworld.xml