# official PHP docker image from https://hub.docker.com/_/php
image: php:5.6

before_script:
- bash ci/docker_install.sh > /dev/null

test:app:
  script:
  - phpunit --configuration phpunit_helloworld.xml